import * as THREE from 'three';
import {
    NoiseModule,
    VelocityOverLifetime,
    SpeedOverLifetime,
    ForceOverLifetime,
    LimitVelocityOverLifetime,
    TransformByNoise,
    ColorOverLifetime,
    ColorBySize,
    ColorBySpeed,
    ColorByDepth,
    DistortionOverLifetime,
    DistortionBySize,
    DistortionBySpeed,
    DistortionByDepth,
    ScaleOverLifetime,
    ScaleBySpeed,
    ScaleByDepth,
    RotationOverLifetime,
    RotationBySize,
    RotationBySpeed,
    RotationByDepth,
    OrientToDirection,
    VelocityBySize,
    VelocityByDepth,
    SpeedBySize,
    SpeedByDepth,
    MassOverLifetime,
    MassBySize,
    MassByDepth,
    Boids,
    SpriteRenderer,
    MeshRenderer,
    LightRenderer,
    TrailRenderer,
    Collision,
} from '@rzmps/rzmps';

export const AUDIO_BUFFER_SOURCE_KEY = '__rzmpsAudioBufferSource';
export const RAW_CODE = Symbol('rawCode');
export const LOD_GUI_KEYS = new Set(['useUpdateLOD', 'updateLOD', 'countLOD', 'compensateSize']);

export const INITIAL_VALUE_DEFAULTS = {
    lifetime: () => 1,
    speed: () => 1,
    position: () => new THREE.Vector3(),
    rotation: () => new THREE.Vector3(),
    scale: () => new THREE.Vector3(1, 1, 1),
    velocity: () => new THREE.Vector3(),
    angularVelocity: () => new THREE.Vector3(),
    scalarVelocity: () => new THREE.Vector3(),
    acceleration: () => new THREE.Vector3(),
    angularAcceleration: () => new THREE.Vector3(),
    scalarAcceleration: () => new THREE.Vector3(),
    color: () => new THREE.Color(1, 1, 1),
    alpha: () => 1,
    mass: () => 0,
    distortionStrength: () => 1,
};

export const DEFAULT_MODULE_FACTORIES = {
    'Velocity Over Lifetime': () => new VelocityOverLifetime({ linear: new THREE.Vector3() }),
    'Speed Over Lifetime': () => new SpeedOverLifetime({ speed: 1 }),
    'Force Over Lifetime': () => new ForceOverLifetime({ force: new THREE.Vector3() }),
    'Limit Velocity Over Lifetime': () => new LimitVelocityOverLifetime({ limit: new THREE.Vector3(10, 10, 10) }),
    'Transform By Noise': () => new TransformByNoise({ strength: new THREE.Vector3(1, 1, 1), frequency: 1 }),
    'Color Over Lifetime': () => new ColorOverLifetime({ color: new THREE.Color(1, 1, 1), alpha: 1 }),
    'Color By Size': () => new ColorBySize({ color: [new THREE.Color(1, 1, 1), new THREE.Color(1, 1, 1)], sizeRange: [0, 10] }),
    'Color By Speed': () => new ColorBySpeed({ color: [new THREE.Color(1, 1, 1), new THREE.Color(1, 1, 1)], speedRange: [0, 10] }),
    'Color By Depth': () => new ColorByDepth({ color: [new THREE.Color(1, 1, 1), new THREE.Color(1, 1, 1)], depthRange: [0, 20] }),
    'Distortion Over Lifetime': () => new DistortionOverLifetime({ distortionStrength: 1 }),
    'Distortion By Size': () => new DistortionBySize({ distortionStrength: [1, 1], sizeRange: [0, 10] }),
    'Distortion By Speed': () => new DistortionBySpeed({ distortionStrength: [1, 1], speedRange: [0, 10] }),
    'Distortion By Depth': () => new DistortionByDepth({ distortionStrength: [1, 1], depthRange: [0, 20] }),
    'Size Over Lifetime': () => new ScaleOverLifetime({ scale: new THREE.Vector3(1, 1, 1) }),
    'Size By Speed': () => new ScaleBySpeed({ scale: [new THREE.Vector3(1, 1, 1), new THREE.Vector3(1, 1, 1)], speedRange: [0, 10] }),
    'Size By Depth': () => new ScaleByDepth({ scale: [new THREE.Vector3(1, 1, 1), new THREE.Vector3(1, 1, 1)], depthRange: [0, 20] }),
    'Rotation Over Lifetime': () => new RotationOverLifetime({ angularVelocity: new THREE.Vector3() }),
    'Rotation By Size': () => new RotationBySize({ angularVelocity: new THREE.Vector3(), sizeRange: [0, 10] }),
    'Rotation By Speed': () => new RotationBySpeed({ angularVelocity: new THREE.Vector3(), speedRange: [0, 10] }),
    'Rotation By Depth': () => new RotationByDepth({ angularVelocity: new THREE.Vector3(), depthRange: [0, 20] }),
    'Orient To Direction': () => new OrientToDirection({ axis: new THREE.Vector3(0, 1, 0) }),
    'Velocity By Size': () => new VelocityBySize({ velocity: new THREE.Vector3(), sizeRange: [0, 10] }),
    'Velocity By Depth': () => new VelocityByDepth({ velocity: new THREE.Vector3(), depthRange: [0, 20] }),
    'Speed By Size': () => new SpeedBySize({ speed: [1, 1], sizeRange: [0, 10] }),
    'Speed By Depth': () => new SpeedByDepth({ speed: [1, 1], depthRange: [0, 20] }),
    'Mass Over Lifetime': () => new MassOverLifetime({ mass: 1 }),
    'Mass By Size': () => new MassBySize({ mass: [1, 1], sizeRange: [0, 10] }),
    'Mass By Depth': () => new MassByDepth({ mass: [1, 1], depthRange: [0, 20] }),
    Boids: () => new Boids({
        octreeOptions: {
            maxDepth: 4,
            particlesPerLeaf: 8,
        },
        alignmentWeight: 1,
        cohesionWeight: 1,
        separationWeight: 1.5,
        affectorWeight: 1,
        affectorDistance: 0,
        steering: 1,
        particleAffectors: [],
    }),
    'Noise Module': () => new NoiseModule('noise'),
    Collision: () => new Collision(),
};

export const DEFAULT_RENDERER_FACTORIES = {
    Sprite: () => new SpriteRenderer(),
    Mesh: () => new MeshRenderer(),
    Light: () => new LightRenderer(),
    Trail: () => new TrailRenderer(),
};
